spring.application.name=${APP_NAME:backend-despacho}
server.port=${SERVER_PORT:3002}
spring.web.allow-cors=true

#spring.datasource.url=${DB_URL:jdbc:mysql://mysql-db:3306/tienda?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.url=${DB_URL:jdbc:mysql://db:3306/tienda}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html